name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      # Checkout the repository code including submodules
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install the necessary dependencies for GitHub Actions
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      # Fetch the ID token
      - name: Get Id Token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      # Build and Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GLACIER_018D51210 }}  # Make sure to set this in Secrets
          action: "upload"
          # Repository/Build Configurations - These values can be configured to match your app requirements
          app_location: "/"  # App source code path
          api_location: "api"  # API source code path - optional
          output_location: "/"  # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          # End of Repository/Build Configurations

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      # This job will close the PR deployment
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"  # Close the PR deployment
